### ISSUE TITLE
지도, 지리 관련 API 조사

### ISSUE THREAD

**Issue by 05Castle** [growing-devs/easy-to-real-estate-frontend#10]
## Description

지도 API 조사하고 어떻게 사용할 지 테스트.

## Todo List

- [x] 사용할 API 정하기

## 기능 테스트

- [x] 주소 검색 
- [x] 지도 표시
- [x] 로드뷰 전환
- [x] 주변 시설 정보 확인

## 알아보기
주소 검색시 부동산 정보(부동산 유형, 면적)를 바로 불러올 수 있는지

**Comment by 05Castle** [comment]
지도 표시를 위해 카카오 맵 api를 활용할 가능성이 높아보인다.
하지만, 해당 카카오 맵 api에는 주소를 받아 지도를 표시해주는 기능은 있지만
자체적으로 주소를 검색하는 기능은 없는 것으로 보인다.
별도의 주소 검색 api가 필요해 보인다.

**Comment by sihyun10** [comment]
https://apis.map.kakao.com/web/sample/roadviewToggle/

**Comment by 05Castle** [comment]
카카오 지도 api에 키워드로 주소를 찾고 목록을 리스트로 표시하는 기능이 있음을 확인했다.
input 창에 입력한 값을 키워드로 카카오 지도 api에 전달하면 주소 검색 기능이 구현될 것으로 보인다.

다만, 이 경우에도 UX/UI 변경은 불가피하다고 여겨진다.
카카오 지도 api만으로는 부동산 유형과 면적 정보를 받아올 수 없기 때문이다.

**Comment by sihyun10** [comment]
지도 위에 특정 장소를 표시하는 마커를 로드뷰에서도 마커로 표시하고, 특정 장소 로드뷰의 파노라마 ID와 시점(ViewPoint)을 설정해, 지도 위의 로드뷰 버튼을 클릭하게 되면 로드뷰가 보여지고, 로드뷰 위의 지도 버튼을 클릭하면 지도가 보여진다. (로드뷰의 파노라마ID, 시점은 Wizard를 사용)

*ex) https://apis.map.kakao.com/web/documentation/#RoadviewClient_getNearestPanoId _ 좌표로 panoid를 찾는 코드 참고

**Comment by 05Castle** [comment]
react-daum-postcode 라이브러리로 daum.Postcode를 리액트에서 쉽게 사용 가능.
react-kakao-maps-sdk 라이브러리로 kakao map API를 리액트에서 쉽게 사용 가능.

하지만 둘 다 공식 라이브러리가 아닌 것으로 보인다.
덕분에 훨씬 쉽게 기능 구현이 가능하지만,
API를 사용함에 있어서 공식이 아닌 라이브러리를 사용해서 개발을 해도 될까?
