### ISSUE TITLE
pdf 드로그앤드롭 기능

### ISSUE THREAD

**Issue by sihyun10** [growing-devs/easy-to-real-estate-frontend#3]
## Description
pdf 파일을 드로그앤드롭 했을때 잘 작동하는지 확인하기

## Todo List

- [x] 드로그앤드롭 기능 테스트하기
- [x] eslint 문법에 맞도록 수정하기

**Comment by 05Castle** [comment]
이슈 모두 해결되었으면, 이슈 close 해주세요.
